
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_css_ViewCSS::getComputedStyle(v8::Handle<v8::Value> val_elt, css::DOMString val_pseudoElt)
{
    return css::ViewCSS::getComputedStyle(val_elt, val_pseudoElt);
}
