
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_css_CSSPrimitiveValue::setFloatValue(short unsigned int val_unitType, double val_floatValue)
{
    css::CSSPrimitiveValue::setFloatValue(val_unitType, val_floatValue);
}
double js_css_CSSPrimitiveValue::getFloatValue(short unsigned int val_unitType)
{
    return css::CSSPrimitiveValue::getFloatValue(val_unitType);
}
void js_css_CSSPrimitiveValue::setStringValue(short unsigned int val_stringType, css::DOMString val_stringValue)
{
    css::CSSPrimitiveValue::setStringValue(val_stringType, val_stringValue);
}
css::DOMString js_css_CSSPrimitiveValue::getStringValue()
{
    return css::CSSPrimitiveValue::getStringValue();
}
v8::Handle<v8::Value> js_css_CSSPrimitiveValue::getCounterValue()
{
    return css::CSSPrimitiveValue::getCounterValue();
}
v8::Handle<v8::Value> js_css_CSSPrimitiveValue::getRectValue()
{
    return css::CSSPrimitiveValue::getRectValue();
}
v8::Handle<v8::Value> js_css_CSSPrimitiveValue::getRGBColorValue()
{
    return css::CSSPrimitiveValue::getRGBColorValue();
}
