
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_CSSStyleDeclaration.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

css::DOMString js_css_CSSStyleDeclaration::getPropertyValue(css::DOMString val_propertyName)
{
    return css::CSSStyleDeclaration::getPropertyValue(val_propertyName);
}
v8::Handle<v8::Value> js_css_CSSStyleDeclaration::getPropertyCSSValue(css::DOMString val_propertyName)
{
    return css::CSSStyleDeclaration::getPropertyCSSValue(val_propertyName);
}
css::DOMString js_css_CSSStyleDeclaration::removeProperty(css::DOMString val_propertyName)
{
    return css::CSSStyleDeclaration::removeProperty(val_propertyName);
}
css::DOMString js_css_CSSStyleDeclaration::getPropertyPriority(css::DOMString val_propertyName)
{
    return css::CSSStyleDeclaration::getPropertyPriority(val_propertyName);
}
void js_css_CSSStyleDeclaration::setProperty(css::DOMString val_propertyName, css::DOMString val_value, css::DOMString val_priority)
{
    css::CSSStyleDeclaration::setProperty(val_propertyName, val_value, val_priority);
}
css::DOMString js_css_CSSStyleDeclaration::item(long unsigned int val_index)
{
    return css::CSSStyleDeclaration::item(val_index);
}

js_css_CSSStyleDeclaration::js_css_CSSStyleDeclaration() {}

js_css_CSSStyleDeclaration::~js_css_CSSStyleDeclaration() {}
