
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_ViewCSS.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_css_ViewCSS::getComputedStyle(v8::Handle<v8::Value> val_elt, css::DOMString val_pseudoElt)
{
    return css::ViewCSS::getComputedStyle(val_elt, val_pseudoElt);
}

js_css_ViewCSS::js_css_ViewCSS() {}

js_css_ViewCSS::~js_css_ViewCSS() {}
