
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_CSSMediaRule.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

long unsigned int js_css_CSSMediaRule::insertRule(css::DOMString val_rule, long unsigned int val_index)
{
    return css::CSSMediaRule::insertRule(val_rule, val_index);
}
void js_css_CSSMediaRule::deleteRule(long unsigned int val_index)
{
    css::CSSMediaRule::deleteRule(val_index);
}

js_css_CSSMediaRule::js_css_CSSMediaRule() {}

js_css_CSSMediaRule::~js_css_CSSMediaRule() {}
