
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_DocumentCSS.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_css_DocumentCSS::getOverrideStyle(v8::Handle<v8::Value> val_elt, css::DOMString val_pseudoElt)
{
    return css::DocumentCSS::getOverrideStyle(val_elt, val_pseudoElt);
}

js_css_DocumentCSS::js_css_DocumentCSS() {}

js_css_DocumentCSS::~js_css_DocumentCSS() {}
