
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
long unsigned int js_css_CSSStyleSheet::insertRule(css::DOMString val_rule, long unsigned int val_index)
{
    return css::CSSStyleSheet::insertRule(val_rule, val_index);
}
void js_css_CSSStyleSheet::deleteRule(long unsigned int val_index)
{
    css::CSSStyleSheet::deleteRule(val_index);
}
