
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_dom_Text::splitText(long unsigned int val_offset)
{
    return dom::Text::splitText(val_offset);
}
