
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_events_EventListener::handleEvent(v8::Handle<v8::Value> val_evt)
{
    events::EventListener::handleEvent(val_evt);
}
