
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_events_EventListener.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

void js_events_EventListener::handleEvent(v8::Handle<v8::Value> val_evt)
{
    events::EventListener::handleEvent(val_evt);
}

js_events_EventListener::js_events_EventListener() {}

js_events_EventListener::~js_events_EventListener() {}
