
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

void js_events_UIEvent::initUIEvent(events::DOMString val_typeArg, bool val_canBubbleArg, bool val_cancelableArg, v8::Handle<v8::Value> val_viewArg, long int val_detailArg)
{
    events::UIEvent::initUIEvent(val_typeArg, val_canBubbleArg, val_cancelableArg, val_viewArg, val_detailArg);
}

js_events_UIEvent::js_events_UIEvent() {}

js_events_UIEvent::~js_events_UIEvent() {}
