
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_events_MutationEvent.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

void js_events_MutationEvent::initMutationEvent(events::DOMString val_typeArg, bool val_canBubbleArg, bool val_cancelableArg, v8::Handle<v8::Value> val_relatedNodeArg, events::DOMString val_prevValueArg, events::DOMString val_newValueArg, events::DOMString val_attrNameArg, short unsigned int val_attrChangeArg)
{
    events::MutationEvent::initMutationEvent(val_typeArg, val_canBubbleArg, val_cancelableArg, val_relatedNodeArg, val_prevValueArg, val_newValueArg, val_attrNameArg, val_attrChangeArg);
}

js_events_MutationEvent::js_events_MutationEvent() {}

js_events_MutationEvent::~js_events_MutationEvent() {}
