
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

void js_events_MouseEvent::initMouseEvent(events::DOMString val_typeArg, bool val_canBubbleArg, bool val_cancelableArg, v8::Handle<v8::Value> val_viewArg, long int val_detailArg, long int val_screenXArg, long int val_screenYArg, long int val_clientXArg, long int val_clientYArg, bool val_ctrlKeyArg, bool val_altKeyArg, bool val_shiftKeyArg, bool val_metaKeyArg, short unsigned int val_buttonArg, v8::Handle<v8::Value> val_relatedTargetArg)
{
    events::MouseEvent::initMouseEvent(val_typeArg, val_canBubbleArg, val_cancelableArg, val_viewArg, val_detailArg, val_screenXArg, val_screenYArg, val_clientXArg, val_clientYArg, val_ctrlKeyArg, val_altKeyArg, val_shiftKeyArg, val_metaKeyArg, val_buttonArg, val_relatedTargetArg);
}

js_events_MouseEvent::js_events_MouseEvent() {}

js_events_MouseEvent::~js_events_MouseEvent() {}
