
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_events_EventTarget.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

void js_events_EventTarget::addEventListener(events::DOMString val_type, v8::Handle<v8::Value> val_listener, bool val_useCapture)
{
    events::EventTarget::addEventListener(val_type, val_listener, val_useCapture);
}
void js_events_EventTarget::removeEventListener(events::DOMString val_type, v8::Handle<v8::Value> val_listener, bool val_useCapture)
{
    events::EventTarget::removeEventListener(val_type, val_listener, val_useCapture);
}
bool js_events_EventTarget::dispatchEvent(v8::Handle<v8::Value> val_evt)
{
    return events::EventTarget::dispatchEvent(val_evt);
}

js_events_EventTarget::js_events_EventTarget() {}

js_events_EventTarget::~js_events_EventTarget() {}
