
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_html2_HTMLInputElement::blur()
{
    html2::HTMLInputElement::blur();
}
void js_html2_HTMLInputElement::focus()
{
    html2::HTMLInputElement::focus();
}
void js_html2_HTMLInputElement::select()
{
    html2::HTMLInputElement::select();
}
void js_html2_HTMLInputElement::click()
{
    html2::HTMLInputElement::click();
}
