
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_html2_HTMLTableElement::createTHead()
{
    return html2::HTMLTableElement::createTHead();
}
void js_html2_HTMLTableElement::deleteTHead()
{
    html2::HTMLTableElement::deleteTHead();
}
v8::Handle<v8::Value> js_html2_HTMLTableElement::createTFoot()
{
    return html2::HTMLTableElement::createTFoot();
}
void js_html2_HTMLTableElement::deleteTFoot()
{
    html2::HTMLTableElement::deleteTFoot();
}
v8::Handle<v8::Value> js_html2_HTMLTableElement::createCaption()
{
    return html2::HTMLTableElement::createCaption();
}
void js_html2_HTMLTableElement::deleteCaption()
{
    html2::HTMLTableElement::deleteCaption();
}
v8::Handle<v8::Value> js_html2_HTMLTableElement::insertRow(long int val_index)
{
    return html2::HTMLTableElement::insertRow(val_index);
}
void js_html2_HTMLTableElement::deleteRow(long int val_index)
{
    html2::HTMLTableElement::deleteRow(val_index);
}
