
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_html2_HTMLFormElement::submit()
{
    html2::HTMLFormElement::submit();
}
void js_html2_HTMLFormElement::reset()
{
    html2::HTMLFormElement::reset();
}
