
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_html2_HTMLAnchorElement.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

void js_html2_HTMLAnchorElement::blur()
{
    html2::HTMLAnchorElement::blur();
}
void js_html2_HTMLAnchorElement::focus()
{
    html2::HTMLAnchorElement::focus();
}

js_html2_HTMLAnchorElement::js_html2_HTMLAnchorElement() {}

js_html2_HTMLAnchorElement::~js_html2_HTMLAnchorElement() {}
