
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_html2_HTMLTableSectionElement.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_html2_HTMLTableSectionElement::insertRow(long int val_index)
{
    return html2::HTMLTableSectionElement::insertRow(val_index);
}
void js_html2_HTMLTableSectionElement::deleteRow(long int val_index)
{
    html2::HTMLTableSectionElement::deleteRow(val_index);
}

js_html2_HTMLTableSectionElement::js_html2_HTMLTableSectionElement() {}

js_html2_HTMLTableSectionElement::~js_html2_HTMLTableSectionElement() {}
