
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_html2_HTMLTextAreaElement.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

void js_html2_HTMLTextAreaElement::blur()
{
    html2::HTMLTextAreaElement::blur();
}
void js_html2_HTMLTextAreaElement::focus()
{
    html2::HTMLTextAreaElement::focus();
}
void js_html2_HTMLTextAreaElement::select()
{
    html2::HTMLTextAreaElement::select();
}

js_html2_HTMLTextAreaElement::js_html2_HTMLTextAreaElement() {}

js_html2_HTMLTextAreaElement::~js_html2_HTMLTextAreaElement() {}
