
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_html2_HTMLOptionsCollection.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_html2_HTMLOptionsCollection::item(long unsigned int val_index)
{
    return html2::HTMLOptionsCollection::item(val_index);
}
v8::Handle<v8::Value> js_html2_HTMLOptionsCollection::namedItem(html2::DOMString val_name)
{
    return html2::HTMLOptionsCollection::namedItem(val_name);
}

js_html2_HTMLOptionsCollection::js_html2_HTMLOptionsCollection() {}

js_html2_HTMLOptionsCollection::~js_html2_HTMLOptionsCollection() {}
