
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

void js_html2_HTMLFormElement::submit()
{
    html2::HTMLFormElement::submit();
}
void js_html2_HTMLFormElement::reset()
{
    html2::HTMLFormElement::reset();
}

js_html2_HTMLFormElement::js_html2_HTMLFormElement() {}

js_html2_HTMLFormElement::~js_html2_HTMLFormElement() {}
