
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_html2_HTMLTableRowElement::insertCell(long int val_index)
{
    return html2::HTMLTableRowElement::insertCell(val_index);
}
void js_html2_HTMLTableRowElement::deleteCell(long int val_index)
{
    html2::HTMLTableRowElement::deleteCell(val_index);
}

js_html2_HTMLTableRowElement::js_html2_HTMLTableRowElement() {}

js_html2_HTMLTableRowElement::~js_html2_HTMLTableRowElement() {}
