
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_html2_HTMLSelectElement::add(v8::Handle<v8::Value> val_element, v8::Handle<v8::Value> val_before)
{
    html2::HTMLSelectElement::add(val_element, val_before);
}
void js_html2_HTMLSelectElement::remove(long int val_index)
{
    html2::HTMLSelectElement::remove(val_index);
}
void js_html2_HTMLSelectElement::blur()
{
    html2::HTMLSelectElement::blur();
}
void js_html2_HTMLSelectElement::focus()
{
    html2::HTMLSelectElement::focus();
}
