
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_ranges_DocumentRange::createRange()
{
    return ranges::DocumentRange::createRange();
}
