
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_stylesheets_MediaList.cpp 36341 2010-11-17 12:32:49Z santonov $
*/

#include "precomp.h"
using namespace v8;

stylesheets::DOMString js_stylesheets_MediaList::item(long unsigned int val_index)
{
    return stylesheets::MediaList::item(val_index);
}
void js_stylesheets_MediaList::deleteMedium(stylesheets::DOMString val_oldMedium)
{
    stylesheets::MediaList::deleteMedium(val_oldMedium);
}
void js_stylesheets_MediaList::appendMedium(stylesheets::DOMString val_newMedium)
{
    stylesheets::MediaList::appendMedium(val_newMedium);
}

js_stylesheets_MediaList::js_stylesheets_MediaList() {}

js_stylesheets_MediaList::~js_stylesheets_MediaList() {}
