
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_stylesheets_StyleSheetList.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_stylesheets_StyleSheetList::item(long unsigned int val_index)
{
    return stylesheets::StyleSheetList::item(val_index);
}

js_stylesheets_StyleSheetList::js_stylesheets_StyleSheetList() {}

js_stylesheets_StyleSheetList::~js_stylesheets_StyleSheetList() {}
