
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_traversal_NodeIterator::nextNode()
{
    return traversal::NodeIterator::nextNode();
}
v8::Handle<v8::Value> js_traversal_NodeIterator::previousNode()
{
    return traversal::NodeIterator::previousNode();
}
void js_traversal_NodeIterator::detach()
{
    traversal::NodeIterator::detach();
}
