
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
short int js_traversal_NodeFilter::acceptNode(v8::Handle<v8::Value> val_n)
{
    return traversal::NodeFilter::acceptNode(val_n);
}
