#ifndef __wiService__
#define __wiService__

/**
@file
Subclass of Service, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing Service */
class wiService : public Service
{
protected:
    wxPanel* m_pVulners;
    wxPanel* m_pReports;
    wxPanel* m_pScripts;

public:
	/** Constructor */
	wiService( wxWindow* parent );
};

#endif // __wiService__
