#ifndef __wiServDialog__
#define __wiServDialog__

/**
@file
Subclass of ServDialog, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing ServDialog */
class wiServDialog : public ServDialog
{
protected:
	// Handlers for ServDialog events.
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	wiServDialog( wxWindow* parent );
};

#endif // __wiServDialog__
