#ifndef __wiMainForm__
#define __wiMainForm__

/**
@file
Subclass of MainForm, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"
#include "wiStatBar.h"

/** Implementing MainForm */
class wiMainForm : public MainForm
{
protected:
    wxPanel* m_pTasks;
    wxPanel* m_pReports;
    wxPanel* m_pSettings;
    wiStatBar* m_statusBar;

    // Handlers for MainForm events.
	void OnClose( wxCloseEvent& event );

public:
	/** Constructor */
	wiMainForm( wxWindow* parent );
};

#endif // __wiMainForm__
