#ifndef __wiObjDialog__
#define __wiObjDialog__

/**
@file
Subclass of ObjDialog, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing ObjDialog */
class wiObjDialog : public ObjDialog
{
protected:
	// Handlers for ServDialog events.
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	wiObjDialog( wxWindow* parent );
};

#endif // __wiObjDialog__
