#ifndef __wiPluginSettings__
#define __wiPluginSettings__

/**
@file
Subclass of PluginSettings, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing PluginSettings */
class wiPluginSettings : public PluginSettings
{
public:
	/** Constructor */
	wiPluginSettings( wxWindow* parent, const wxString& description );
};

#endif // __wiPluginSettings__
