#ifndef __wiSettings__
#define __wiSettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing Settings */
class wiSettings : public Settings
{
protected:
	// Handlers for Settings events.
	void OnConnect( wxCommandEvent& event );
	void OnAddServer( wxCommandEvent& event );
	void OnEditServer( wxCommandEvent& event );
	void OnDelServer( wxCommandEvent& event );
	void OnLangChange( wxCommandEvent& event );
	void OnStorageChange( wxCommandEvent& event );
	void OnPlgRefresh( wxCommandEvent& event );
	void OnSrvStop( wxCommandEvent& event );
	void OnServerLogs( wxCommandEvent& event );

	void InitPluginsGrid();

public:
	/** Constructor */
	wiSettings( wxWindow* parent );
};

#endif // __wiSettings__
