#ifndef __wiSettings__
#define __wiSettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"
#include "messages.h"

/** Implementing Settings */
class wiSettings : public Settings
{
protected:
	// Handlers for Settings events.
    void OnChangeSrv( wxCommandEvent& event );
	void OnConnect( wxCommandEvent& event );
	void OnAddServer( wxCommandEvent& event );
	void OnEditServer( wxCommandEvent& event );
	void OnDelServer( wxCommandEvent& event );
	void OnLangChange( wxCommandEvent& event );
	void OnStorageChange( wxCommandEvent& event );
	void OnPlgRefresh( wxCommandEvent& event );
	void OnSrvRestart( wxCommandEvent& event );
	void OnSrvStop( wxCommandEvent& event );
	void OnServerLogs( wxCommandEvent& event );

    // functions
	void InitPluginsGrid();
	void LoadConnections();

	// data members
	bool connected;

public:
	/** Constructor */
	wiSettings( wxWindow* parent );

	void Connected();
	void Disconnected(bool forced = true);

	wxString GetLanguage();
	bool GetLogging();
	void SetServerVersion(const wxString& ver);
	void ShowPluginsList(PluginList* plugList);
};

#endif // __wiSettings__
