#ifndef __wiTasks__
#define __wiTasks__

/**
@file
Subclass of Tasks, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing Tasks */
class wiTasks : public Tasks
{
protected:
	// Handlers for Tasks events.
	void OnAddObject( wxCommandEvent& event );
	void OnEditObject( wxCommandEvent& event );
	void OnDelObject( wxCommandEvent& event );
	void OnTaskKillFocus( wxFocusEvent& event );
	void OnSelectObject( wxListEvent& event );
	void OnChangeProfile( wxCommandEvent& event );
	void OnAddProfile( wxCommandEvent& event );
	void OnCopyProfile( wxCommandEvent& event );
	void OnDelProfile( wxCommandEvent& event );
	void OnTaskApply( wxCommandEvent& event );
	void OnRunTask( wxCommandEvent& event );
	void OnAddPlugin( wxCommandEvent& event );
	void OnRemovePlugin( wxCommandEvent& event );
	void OnOptionsPageChanging( wxListbookEvent& event );
	void OnPauseTask( wxCommandEvent& event );
	void OnCancelTask( wxCommandEvent& event );
	void OnSortItems( wxListEvent& event );
	void OnTaskSelected( wxListEvent& event );
	
public:
	/** Constructor */
	wiTasks( wxWindow* parent );
};

#endif // __wiTasks__
