#ifndef __wiReports__
#define __wiReports__

/**
@file
Subclass of Reports, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing Reports */
class wiReports : public Reports
{
protected:
	// Handlers for Reports events.
	void OnReportsRefresh( wxCommandEvent& event );
	void OnReportsFilter( wxCommandEvent& event );
	void OnReportTskFilter( wxCommandEvent& event );
	void OnReportsDate( wxCommandEvent& event );
	void OnReportDateFilter( wxDateEvent& event );
	void OnReportsStatus( wxCommandEvent& event );
	void OnReportsSave( wxCommandEvent& event );
	void OnReporterChanged( wxCommandEvent& event );
	void OnReporterApply( wxCommandEvent& event );
	void OnReporterLoad( wxCommandEvent& event );
	void OnReportExpand( wxTreeEvent& event );
	void OnReportSelected( wxTreeEvent& event );
	
public:
	/** Constructor */
	wiReports( wxWindow* parent );
};

#endif // __wiReports__
