/*
    webInventory is the web-application audit programm
    Copyright (C) 2009 Andrew Abramov stinger911@gmail.com

    This file is part of webInventory

    webInventory is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    webInventory is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with webInventory.  If not, see <http://www.gnu.org/licenses/>.
*//************************************************************
 * @file      wiVulnDB.cpp
 * @brief     Code for MainForm class
 * @author    Tursas Pohielainen (tursasp@gmail.com)
 * @date      05.10.2009
 **************************************************************/
#ifndef __wiVulnDB__
#define __wiVulnDB__

/**
@file
Subclass of VulnDB, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing VulnDB */
class wiVulnDB : public VulnDB
{
protected:
	// Handlers for VulnDB events.
	void OnTreeRefresh( wxCommandEvent& event );
	void OnDbSlice( wxCommandEvent& event );
	void OnAddObj( wxCommandEvent& event );
	void OnCloneObj( wxCommandEvent& event );
	void OnDelObj( wxCommandEvent& event );
	void OnSaveObj( wxCommandEvent& event );
	void OnVulnerSelect( wxTreeEvent& event );
	void OnDataChanged( wxCommandEvent& event );
	// wxScintilla functions
    void OnMarginClick (wxScintillaEvent &event);
	void OnCharAdded (wxScintillaEvent &event);

	// functions
	bool ContinueUnsaved();
	void DrawTree();
	void SaveVulner();

	// members
	bool m_bDataChanged;
	bool m_forceSelect;
	bool m_inUpdate;

public:
	/** Constructor */
	wiVulnDB( wxWindow* parent );
};

#endif // __wiVulnDB__
