
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_css_CSSRuleList::item(long unsigned int val_index)
{
    return css::CSSRuleList::item(val_index);
}

js_css_CSSRuleList::js_css_CSSRuleList() {}

js_css_CSSRuleList::~js_css_CSSRuleList() {}
