
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_DOMImplementationCSS.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_css_DOMImplementationCSS::createCSSStyleSheet(css::DOMString val_title, css::DOMString val_media)
{
    return css::DOMImplementationCSS::createCSSStyleSheet(val_title, val_media);
}

js_css_DOMImplementationCSS::js_css_DOMImplementationCSS() {}

js_css_DOMImplementationCSS::~js_css_DOMImplementationCSS() {}
