
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_css_CSSRuleList.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_css_CSSRuleList::item(long unsigned int val_index)
{
    return css::CSSRuleList::item(val_index);
}

js_css_CSSRuleList::js_css_CSSRuleList() {}

js_css_CSSRuleList::~js_css_CSSRuleList() {}
