
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_css_DOMImplementationCSS::createCSSStyleSheet(css::DOMString val_title, css::DOMString val_media)
{
    return css::DOMImplementationCSS::createCSSStyleSheet(val_title, val_media);
}

js_css_DOMImplementationCSS::js_css_DOMImplementationCSS() {}

js_css_DOMImplementationCSS::~js_css_DOMImplementationCSS() {}
