
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_dom_Text.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_dom_Text::splitText(long unsigned int val_offset)
{
    return dom::Text::splitText(val_offset);
}

js_dom_Text::js_dom_Text() {}

js_dom_Text::~js_dom_Text() {}
