
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_dom_CharacterData.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

std::string js_dom_CharacterData::substringData(long unsigned int val_offset, long unsigned int val_count)
{
    return dom::CharacterData::substringData(val_offset, val_count);
}
void js_dom_CharacterData::appendData(std::string val_arg)
{
    dom::CharacterData::appendData(val_arg);
}
void js_dom_CharacterData::insertData(long unsigned int val_offset, std::string val_arg)
{
    dom::CharacterData::insertData(val_offset, val_arg);
}
void js_dom_CharacterData::deleteData(long unsigned int val_offset, long unsigned int val_count)
{
    dom::CharacterData::deleteData(val_offset, val_count);
}
void js_dom_CharacterData::replaceData(long unsigned int val_offset, long unsigned int val_count, std::string val_arg)
{
    dom::CharacterData::replaceData(val_offset, val_count, val_arg);
}

js_dom_CharacterData::js_dom_CharacterData() {}

js_dom_CharacterData::~js_dom_CharacterData() {}
