
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_events_Event::stopPropagation()
{
    events::Event::stopPropagation();
}
void js_events_Event::preventDefault()
{
    events::Event::preventDefault();
}
void js_events_Event::initEvent(events::DOMString val_eventTypeArg, bool val_canBubbleArg, bool val_cancelableArg)
{
    events::Event::initEvent(val_eventTypeArg, val_canBubbleArg, val_cancelableArg);
}
