
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_events_DocumentEvent::createEvent(events::DOMString val_eventType)
{
    return events::DocumentEvent::createEvent(val_eventType);
}

js_events_DocumentEvent::js_events_DocumentEvent() {}

js_events_DocumentEvent::~js_events_DocumentEvent() {}
