
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
void js_html2_HTMLAnchorElement::blur()
{
    html2::HTMLAnchorElement::blur();
}
void js_html2_HTMLAnchorElement::focus()
{
    html2::HTMLAnchorElement::focus();
}
