
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_ranges_DocumentRange::createRange()
{
    return ranges::DocumentRange::createRange();
}

js_ranges_DocumentRange::js_ranges_DocumentRange() {}

js_ranges_DocumentRange::~js_ranges_DocumentRange() {}
