
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include "precomp.h"
using namespace v8;

v8::Handle<v8::Value> js_stylesheets_StyleSheetList::item(long unsigned int val_index)
{
    return stylesheets::StyleSheetList::item(val_index);
}

js_stylesheets_StyleSheetList::js_stylesheets_StyleSheetList() {}

js_stylesheets_StyleSheetList::~js_stylesheets_StyleSheetList() {}
