
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id$
*/

#include <html_js.h>
using namespace v8;
v8::Handle<v8::Value> js_traversal_TreeWalker::parentNode()
{
    return traversal::TreeWalker::parentNode();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::firstChild()
{
    return traversal::TreeWalker::firstChild();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::lastChild()
{
    return traversal::TreeWalker::lastChild();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::previousSibling()
{
    return traversal::TreeWalker::previousSibling();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::nextSibling()
{
    return traversal::TreeWalker::nextSibling();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::previousNode()
{
    return traversal::TreeWalker::previousNode();
}
v8::Handle<v8::Value> js_traversal_TreeWalker::nextNode()
{
    return traversal::TreeWalker::nextNode();
}
