
/*
  DO NOT EDIT!
  This file has been generated by generate_sources.py script.
  $Id: js_traversal_NodeIterator.cpp 36276 2010-11-15 14:56:24Z santonov $
*/

#include <html_js.h>
using namespace v8;

v8::Handle<v8::Value> js_traversal_NodeIterator::nextNode()
{
    return traversal::NodeIterator::nextNode();
}
v8::Handle<v8::Value> js_traversal_NodeIterator::previousNode()
{
    return traversal::NodeIterator::previousNode();
}
void js_traversal_NodeIterator::detach()
{
    traversal::NodeIterator::detach();
}

js_traversal_NodeIterator::js_traversal_NodeIterator() {}

js_traversal_NodeIterator::~js_traversal_NodeIterator() {}
