#ifndef __srSetupDlg__
#define __srSetupDlg__

/**
@file
Subclass of SetupDlg, which is generated by wxFormBuilder.
*/

#include "wxGuiData.h"

/** Implementing SetupDlg */
class SrSetupDlg : public SetupDlg
{
protected:
	// Handlers for SetupDlg events.
	void OnFileOpen( wxFileDirPickerEvent& event );
	void OnTxtCopy( wxCommandEvent& event );
	void OnTxtCut( wxCommandEvent& event );
	void OnTxtPaste( wxCommandEvent& event );
	void OnTxtSave( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	
public:
	/** Constructor */
	SrSetupDlg( wxWindow* parent );
};

#endif // __srSetupDlg__
