#ifndef __wiMainForm__
#define __wiMainForm__

/**
@file
Subclass of MainForm, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing MainForm */
class wiMainForm : public MainForm
{
public:
	/** Constructor */
	wiMainForm( wxWindow* parent );
};

#endif // __wiMainForm__
