#ifndef __wiPlgSelector__
#define __wiPlgSelector__

/**
@file
Subclass of PlgSelector, which is generated by wxFormBuilder.
*/

#include "wiGuiData.h"

/** Implementing PlgSelector */
class wiPlgSelector : public PlgSelector
{
protected:
	// Handlers for PlgSelector events.
	void OnOK( wxCommandEvent& event );

public:
	/** Constructor */
	wiPlgSelector( wxWindow* parent );

	wxTreeItemId m_selected;
};

#endif // __wiPlgSelector__
